export const STATUS_BLOCKER_CODES = {
    APPLICATION_NOT_STARTED: 'APPLICATION_NOT_STARTED',
    IDENTITY_REQUIRED: 'IDENTITY_REQUIRED',
    LIVENESS_REQUIRED: 'LIVENESS_REQUIRED',
    CONSENTS_REQUIRED: 'CONSENTS_REQUIRED',
    DOCUMENTS_REQUIRED: 'DOCUMENTS_REQUIRED',
    RESUBMISSION_REQUIRED: 'RESUBMISSION_REQUIRED',
    ADMISSION_REJECTED: 'ADMISSION_REJECTED',
    EXCEPTION_REVIEW_REQUIRED: 'EXCEPTION_REVIEW_REQUIRED',
    APPEAL_PENDING: 'APPEAL_PENDING',
    AUDIT_REVIEW_PENDING: 'AUDIT_REVIEW_PENDING',
    AI_DECISION_PENDING: 'AI_DECISION_PENDING',
    SOUL_ISSUANCE_PENDING: 'SOUL_ISSUANCE_PENDING',
    ACCOUNT_FROZEN: 'ACCOUNT_FROZEN',
    LEGACY_REVIEW_STAGE: 'LEGACY_REVIEW_STAGE',
} as const;

export type StatusBlockerCode = (typeof STATUS_BLOCKER_CODES)[keyof typeof STATUS_BLOCKER_CODES];

const STATUS_BLOCKER_CODE_SET = new Set<string>(Object.values(STATUS_BLOCKER_CODES));

export function isStatusBlockerCode(value: string): value is StatusBlockerCode {
    return STATUS_BLOCKER_CODE_SET.has(value);
}

