export const STATUS_DECISION_REASON_CODES = {
    PRECONDITION_INCOMPLETE: 'PRECONDITION_INCOMPLETE',
    MISSING_REQUIRED_DOCUMENTS: 'MISSING_REQUIRED_DOCUMENTS',
    DOCUMENT_REJECTED: 'DOCUMENT_REJECTED',
    DOCS_FLAGGED_FOR_RESUBMIT: 'DOCS_FLAGGED_FOR_RESUBMIT',
    AI_PROCESSING_INCOMPLETE: 'AI_PROCESSING_INCOMPLETE',
    AI_HARD_REJECT_SIGNAL: 'AI_HARD_REJECT_SIGNAL',
    AI_CONFIDENCE_MISSING: 'AI_CONFIDENCE_MISSING',
    CROSS_DOCUMENT_CONFLICT: 'CROSS_DOCUMENT_CONFLICT',
    VERY_LOW_CONFIDENCE: 'VERY_LOW_CONFIDENCE',
    LOW_CONFIDENCE_EXCEPTION: 'LOW_CONFIDENCE_EXCEPTION',
    LOW_CONFIDENCE_RESUBMIT: 'LOW_CONFIDENCE_RESUBMIT',
    AI_RULES_APPROVED: 'AI_RULES_APPROVED',
} as const;

export type StatusDecisionReasonCode =
    (typeof STATUS_DECISION_REASON_CODES)[keyof typeof STATUS_DECISION_REASON_CODES];

const STATUS_DECISION_REASON_CODE_SET = new Set<string>(Object.values(STATUS_DECISION_REASON_CODES));

export function isStatusDecisionReasonCode(value: string): value is StatusDecisionReasonCode {
    return STATUS_DECISION_REASON_CODE_SET.has(value);
}
