/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface FraudRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "owner" | "reportFraud" | "submitAnchor"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AnchorSubmitted" | "FraudReported"
  ): EventFragment;

  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reportFraud",
    values: [BytesLike, BytesLike, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitAnchor",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reportFraud",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitAnchor",
    data: BytesLike
  ): Result;
}

export namespace AnchorSubmittedEvent {
  export type InputTuple = [
    root: BytesLike,
    batchEnd: BigNumberish,
    schemaVersion: BigNumberish
  ];
  export type OutputTuple = [
    root: string,
    batchEnd: bigint,
    schemaVersion: bigint
  ];
  export interface OutputObject {
    root: string;
    batchEnd: bigint;
    schemaVersion: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FraudReportedEvent {
  export type InputTuple = [
    userIdHash: BytesLike,
    verificationIdHash: BytesLike,
    payloadHash: BytesLike,
    anchorId: BigNumberish,
    fraudType: BigNumberish
  ];
  export type OutputTuple = [
    userIdHash: string,
    verificationIdHash: string,
    payloadHash: string,
    anchorId: bigint,
    fraudType: bigint
  ];
  export interface OutputObject {
    userIdHash: string;
    verificationIdHash: string;
    payloadHash: string;
    anchorId: bigint;
    fraudType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FraudRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): FraudRegistry;
  waitForDeployment(): Promise<this>;

  interface: FraudRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  owner: TypedContractMethod<[], [string], "view">;

  reportFraud: TypedContractMethod<
    [
      userIdHash: BytesLike,
      verificationIdHash: BytesLike,
      payloadHash: BytesLike,
      anchorId: BigNumberish,
      fraudType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  submitAnchor: TypedContractMethod<
    [root: BytesLike, batchEnd: BigNumberish, schemaVersion: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reportFraud"
  ): TypedContractMethod<
    [
      userIdHash: BytesLike,
      verificationIdHash: BytesLike,
      payloadHash: BytesLike,
      anchorId: BigNumberish,
      fraudType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitAnchor"
  ): TypedContractMethod<
    [root: BytesLike, batchEnd: BigNumberish, schemaVersion: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AnchorSubmitted"
  ): TypedContractEvent<
    AnchorSubmittedEvent.InputTuple,
    AnchorSubmittedEvent.OutputTuple,
    AnchorSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "FraudReported"
  ): TypedContractEvent<
    FraudReportedEvent.InputTuple,
    FraudReportedEvent.OutputTuple,
    FraudReportedEvent.OutputObject
  >;

  filters: {
    "AnchorSubmitted(bytes32,uint64,uint32)": TypedContractEvent<
      AnchorSubmittedEvent.InputTuple,
      AnchorSubmittedEvent.OutputTuple,
      AnchorSubmittedEvent.OutputObject
    >;
    AnchorSubmitted: TypedContractEvent<
      AnchorSubmittedEvent.InputTuple,
      AnchorSubmittedEvent.OutputTuple,
      AnchorSubmittedEvent.OutputObject
    >;

    "FraudReported(bytes32,bytes32,bytes32,uint256,uint8)": TypedContractEvent<
      FraudReportedEvent.InputTuple,
      FraudReportedEvent.OutputTuple,
      FraudReportedEvent.OutputObject
    >;
    FraudReported: TypedContractEvent<
      FraudReportedEvent.InputTuple,
      FraudReportedEvent.OutputTuple,
      FraudReportedEvent.OutputObject
    >;
  };
}
