/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FraudRegistry } from "./FraudRegistry";
export * as factories from "./factories";
export { FraudRegistry__factory } from "./factories/FraudRegistry__factory";
